# Generated by Django 5.1.7 on 2025-03-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_remove_student_is_staff_remove_student_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_superuser',
        ),
    ]
