# Generated by Django 5.1.7 on 2025-03-20 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_assessment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'No se permiten calificaciones menores a 1.0'), django.core.validators.MaxValueValidator(5, 'No se permiten calificaciones mayores a 5.0')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', 'El código deber ser un numero de max 10 dígitos')]),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dni',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8,10}$', 'La cédula deber ser un numero de max 10 dígitos')]),
        ),
    ]
