# Generated by Django 5.1.7 on 2025-03-20 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_assessment_rating_alter_student_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'No se permiten calificaciones menores a 1'), django.core.validators.MaxValueValidator(5, 'No se permiten calificaciones mayores a 5')]),
        ),
    ]
